AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  WriteLogsKeyEncrypted:
    Fn::Not:
    - Fn::Equals:
      - Ref: WriteLogsKeyEncrypted
      - ''
  WriteLogsKeyPlaintext:
    Fn::Not:
    - Fn::Equals:
      - Ref: WriteLogsKey
      - ''
Description: Scalyr CloudWatch Logs Importer
Outputs:
  CloudWatchStreamerArn:
    Description: The arn of the CloudWatch Streamer function.
    Value:
      Fn::GetAtt:
      - CloudWatchStreamerFunction
      - Arn
  CloudWatchSubscriberArn:
    Description: The arn of the CloudWatch Subscriber function.
    Value:
      Fn::GetAtt:
      - CloudWatchSubscriberFunction
      - Arn
Parameters:
  AutoSubscribeLogGroups:
    AllowedValues:
    - true
    - false
    Default: false
    Description: Automatically subscribe the logGroups defined in LogGroupOptions
      to the CloudWatch Streamer Lambda function
    Type: String
  BaseUrl:
    AllowedValues:
    - https://www.scalyr.com
    - https://eu.scalyr.com
    Default: https://www.scalyr.com
    Description: Base URL of the Scalyr API
    Type: String
  Debug:
    AllowedValues:
    - true
    - false
    Default: false
    Description: Enable debug logging of each request
    Type: String
  LogGroupOptions:
    Default: '{}'
    Description: Valid JSON string to customise log delivery
    Type: String
  WriteLogsKey:
    Default: ''
    Description: Use this or WriteLogsKeyEncrypted. The Scalyr API key that allows
      write access to Scalyr logs
    Type: String
  WriteLogsKeyEncrypted:
    Default: ''
    Description: Use this or WriteLogsKey. The encrypted Scalyr API key that allows
      write access to Scalyr logs
    Type: String
Resources:
  CloudWatchStreamerFunction:
    Properties:
      CodeUri: s3://scalyr-aws-serverless/cloudwatch_logs/fc8bb8ca8ccfc813dcd97b7adeb2740a
      Environment:
        Variables:
          BASE_URL:
            Ref: BaseUrl
          DEBUG:
            Ref: Debug
          LOG_GROUP_OPTIONS:
            Ref: LogGroupOptions
          WRITE_LOGS_KEY:
            Fn::If:
            - WriteLogsKeyPlaintext
            - Ref: WriteLogsKey
            - Ref: AWS::NoValue
          WRITE_LOGS_KEY_ENCRYPTED:
            Fn::If:
            - WriteLogsKeyEncrypted
            - Ref: WriteLogsKeyEncrypted
            - Ref: AWS::NoValue
      Handler: main.lambda_handler
      Policies:
      - Ref: KMSDecryptPolicy
      Runtime: python3.7
    Type: AWS::Serverless::Function
  CloudWatchSubscriber:
    Properties:
      AccountId:
        Ref: AWS::AccountId
      AutoSubscribeLogGroups:
        Ref: AutoSubscribeLogGroups
      DestinationArn:
        Fn::GetAtt:
        - CloudWatchStreamerFunction
        - Arn
      LogGroupOptions:
        Ref: LogGroupOptions
      Region:
        Ref: AWS::Region
      ServiceToken:
        Fn::GetAtt:
        - CloudWatchSubscriberFunction
        - Arn
    Type: Custom::CustomResource
  CloudWatchSubscriberFunction:
    Properties:
      CodeUri: s3://scalyr-aws-serverless/cloudwatch_logs/b8fab41dab343214cf464c6b49f2a55c
      Handler: main.lambda_handler
      Policies:
      - Ref: CloudWatchSubscriberPolicy
      Runtime: python3.7
      Timeout: 300
    Type: AWS::Serverless::Function
  CloudWatchSubscriberPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - lambda:AddPermission
          - lambda:RemovePermission
          - logs:DescribeLogGroups
          - logs:DeleteSubscriptionFilter
          - logs:PutSubscriptionFilter
          Effect: Allow
          Resource: '*'
        Version: 2012-10-17
    Type: AWS::IAM::ManagedPolicy
  KMSDecryptPolicy:
    Properties:
      PolicyDocument:
        Statement:
        - Action:
          - kms:Decrypt
          Effect: Allow
          Resource:
            Fn::Sub: arn:aws:kms:${AWS::Region}:${AWS::AccountId}:key/*
        Version: 2012-10-17
    Type: AWS::IAM::ManagedPolicy
Transform: AWS::Serverless-2016-10-31
